name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pnpm install
    - run: pnpm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        tag: '0.0.2'
        url: 'https://github.com/example/tool'
        description: 'a description'
        buildType: Go
        main: 'main.go'
        homepage: 'https://github.com/example/tool'
        licenseName: 'MIT'
        formulaName: 'Tool'
        commandName: 'tool'
    - name: Check if file exists
      run: if [[ -e Formula/tool.rb ]]; then echo 'Success'; else exit 1; fi
